# Generated by Django 3.2.3 on 2021-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Table',
            fields=[
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
