# Generated by Django 3.2.3 on 2021-06-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=30)),
                ('TaskDescription', models.CharField(max_length=150)),
                ('Priority', models.CharField(max_length=2)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user_table')),
            ],
        ),
    ]
