# Generated by Django 3.2.3 on 2021-06-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_details_taskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_details',
            name='TaskName',
            field=models.CharField(max_length=50),
        ),
    ]
