# Generated by Django 3.2.3 on 2021-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_details_taskname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_details',
            name='Day',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
